# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad85a2954d05d8a5d9157490095324d4d45bdfa0967e3b43db8cb5b2d83140e4edab5d445fdcd3798d08cac60140ab3abef46f01c900f77677eca7a09e61cba4

test:
  secret_key_base: 0529fc65cf9e58c41e1a4b92b3c4f09ec8514f2fabeccdef3917d7bb75f166637511f1b917ef5c6a62d23c89111e36c0684ce497d7d88ad15add0d53c1a773f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
